// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WpfApp1.Warehouse.Data;

#nullable disable

namespace WpfApp1.Warehouse.Migrations
{
    [DbContext(typeof(WarehouseDbContext))]
    partial class WarehouseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("WpfApp1.Warehouse.Data.Models.Box", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PalletId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PalletId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PalletId1");

                    b.ToTable("Boxes");
                });

            modelBuilder.Entity("WpfApp1.Warehouse.Data.Models.Pallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pallets");
                });

            modelBuilder.Entity("WpfApp1.Warehouse.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoxFormat")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("TEXT");

                    b.Property<int>("BoxId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gtin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PalletFormat")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Volume")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("BoxId1");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WpfApp1.Warehouse.Data.Models.Box", b =>
                {
                    b.HasOne("WpfApp1.Warehouse.Data.Models.Pallet", "Pallet")
                        .WithMany("Boxes")
                        .HasForeignKey("PalletId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pallet");
                });

            modelBuilder.Entity("WpfApp1.Warehouse.Data.Models.Product", b =>
                {
                    b.HasOne("WpfApp1.Warehouse.Data.Models.Box", "Box")
                        .WithMany()
                        .HasForeignKey("BoxId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Box");
                });

            modelBuilder.Entity("WpfApp1.Warehouse.Data.Models.Pallet", b =>
                {
                    b.Navigation("Boxes");
                });
#pragma warning restore 612, 618
        }
    }
}
